# Generated by Django 4.2.7 on 2023-12-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='titulo',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
